src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuthorRepository")
 */
class Author
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * 
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Имя не может быть менее {{ limit }} символов.",
     *      maxMessage = "Имя не может быть длиннее {{ limit }} символов."
     * )
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Фамилия не может быть менее {{ limit }} символов.",
     *      maxMessage = "Фамилия не может быть длиннее {{ limit }} символов."
     * )
     */
    private $Surname;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Book", mappedBy="author")
     */
    private $books;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;
        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->Surname;
    }

    public function setSurname(string $Surname): self
    {
        $this->Surname = $Surname;
        return $this;
    }

    //Получение списка книг Автора
    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks()
    {
        return $this->books;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class MainController extends AbstractController {

    /**
     * @Route("/", name="mainPage")
     */
    public function index() {
        $repository = $this->getDoctrine()->getRepository(Author::class);
        $authors = $repository->findAll(); //Выбрать ВСЕ объекты класса Author 

        return $this->render('main/index.html.twig', [
                    'authors' => $authors,
        ]); //Возвращаем (отображаем) страницу шаблона и передаём переменную $authors
    }

    /**
     * @Route("/login", name="login")
     */
    public function login(Request $request, AuthenticationUtils $authUtils) {
        // получить ошибку входа, если она есть
        $error = $authUtils->getLastAuthenticationError();
        return $this->render('main/login.html.twig', array(
                    'error' => $error,
        ));
    }

    /**
     * @Route("/logout", name="logout")
     */
    public function logout() {
        return $this->redirectToRoute('mainPage');
    }

}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Список авторов {% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        <div class="content w-50">
            <div class="title text-center h1 pb-5 pt-5">
                Список авторов
            </div>

            {% for author in authors %}
                <div class="alert bg-light border border-primary rounded-pill" role="alert">
                    <div class="row">
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    {{ author.name }} {{ author.surname }}
                                </div>
                                {% if is_granted('ROLE_ADMIN') %}
                                    <div class="col-3 text-center">
                                        <a href="{{ path('author', {'id': author.id}) }}" class="btn btn-outline-dark btn-sm">
                                            Редактировать
                                        </a>
                                    </div>
                                {% endif %}
                            </div>                       
                        </div>
                        <div class="col-2 text-center">
                            <a href="{{ path('books', {'id': author.id}) }}" class="btn btn-outline-success btn-sm">
                                Список книг
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}

            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('newAuthorPage') }}" id="btn-exit" class="btn btn-outline-info btn-lg btn-block mt-2" role="button" aria-pressed="true">Добавить автора</a>
            {% endif %}

            {% if (is_granted('IS_AUTHENTICATED_FULLY')==false) %}
                <a href="{{ path('login') }}" id="btn-exit" class="btn btn-outline-info btn-lg btn-block mt-2" role="button" aria-pressed="true">Войти</a>
            {% endif %}

            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                <a href="{{ path('logout') }}" id="btn-exit" class="btn btn-outline-info btn-lg btn-block mt-2" role="button" aria-pressed="true">Выход</a>
            {% endif %}

        </div>
    </div>
{% endblock %}

templates/main/login.html.twig
{% extends 'base.html.twig' %}

{% block title %} Авторизация {% endblock %}

{% block body %}

    {% if error %}
        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    <form action="{{ path('login') }}" method="post">
        <label for="username">Username:</label>
        <input type="text" id="username" name="_username"/>

        <label for="password">Password:</label>
        <input type="password" id="password" name="_password" />

        <input type="hidden" name="_target_path" value="/" />

        <button type="submit">login</button>
    </form>


{% endblock %}